# AUTOGENERATED! DO NOT EDIT! File to edit: ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb.

# %% auto #0
__all__ = ['pca_transform', 'closest_val', 'make_quant', 'make_white_matter_df', 'neighbors', 'mk_outline', 'blur_smooth',
           'iter_smooth', 'mk_outline_2', 'blur_smooth_2', 'solidify', 'infill_mask', 'get_midpoints', 'make_scaled_df',
           'infill_mask_complex', 'd_scale', 'mk_tile_plot', 'mk_pivot', 'wm_annot', 'mk_pivot_table', 'matr_expand',
           'image_trim', 'tiff_write', 'img_disp', 'mk_tiff']

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #1c334d7e-8367-45bd-8f32-7384efd38b73
#General data-manipulation packages.
import pandas as pd
import matplotlib #Purely for the version info (Not stored in sub-objects)
import matplotlib.pyplot as plt
import matplotlib.image as img
import mpl_toolkits
import mpl_toolkits.mplot3d
import sklearn #Purely for the version info...
from sklearn.decomposition import PCA
from sklearn import preprocessing as pre
import numpy as np
import seaborn as sns

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #a1b16ca1-bc71-461b-94e2-c6aa0622a49d
import statistics
import math

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #672e63bd-26ad-47f2-8655-db2c76f42b38
import random
import cv2 as cv
import os

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #af37dac0-95ab-4f42-8bf5-53ef6c134f66
import sys

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #474bbe50-c287-46c6-9f69-a4083e4b5462
# Below are the versions of all the required packages that the module was written with.
# If anything is updated, and stops working, check against these to see what might be the issue:

#pandas version:  2.2.2
#matplotlib version:  3.9.0
#sklearn version:  1.5.0
#numpy version:  1.26.4
#seaborn version:  0.13.2
#cv2 version:  4.12.0
#Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
#--Contains statistics, math, random, os & sys

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #243349ad-22e9-419b-a5f4-cdbd77eaf24c
def pca_transform(df):
    pca = PCA(n_components=1)  # Reduce to 1 principal component
    principal_components = pca.fit_transform(df.drop(columns = ['X Coordinate', 'Y Coordinate']))
    
    #pca_df = pd.DataFrame(data=principal_components, columns=['Marker'])

    #Create new dataframe with just the marker.
    # pca_df = df[['X Coordinate', 'Y Coordinate']]
    pca_df = df[['X Coordinate', 'Y Coordinate']].copy()         #---- Change one line, get rid of an annoying warning.
    pca_df['Marker'] = pd.DataFrame(data=principal_components)

    #Re-scale PCA values to between 0-1, to get rid of negative values.
    
    #create the numpy array
    x = np.array(pca_df['Marker'])
    #reshape array so that it works with sklearn
    x = x.reshape(-1, 1)
    #normalize all values to be between 0 and 1
    x_norm = pre.MinMaxScaler().fit_transform(x)
    #unpack this [1,1] matrix back into a list
    x_nl = []
    for i in x_norm:
        x_nl.append(i[0])
    #replace the 'Marker' column with these normalized values
    pca_df['Marker'] = x_nl

    return(pca_df)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #890ee4e0-0b33-4f1b-ab22-75fb48d31af4
def closest_val(value_list, target_value):
    # The key function tells min() *how* to compare the items.
    # It calculates the absolute difference: |x - target_value|
    return min(value_list, key=lambda x: abs(x - target_value))

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #eecf5aec-8a77-4f5a-b0c2-e928c3f38b53
def make_quant(white_matter_df, q_factor):
    #q_factor needs to be an integer here:
    if q_factor.is_integer():
        #Make sure it's in integer format.
        q_factor = int(q_factor)
    else:
        print("ERROR! 'q_factor' must be a whole number.")

    #Determine the range along which we need to quantize.
    max_val = max(max(white_matter_df['X Coordinate']),max(white_matter_df['Y Coordinate']))
    #We set the limit of the range to be greater than the maximum possible value in either axis, and add one more interval just in-case it rounds down.
    lim = round(max_val/q_factor)*q_factor + q_factor
    #Create list of possible values. Not inclusive of the top-most value.
    vals = list(range(0, lim, q_factor))
    #And, we output the midpoint pf each range,
    midpoints = [item + (q_factor/2) for item in vals]
    #-----
    # This is very important. If the number possible quantized points along a range = n,
    # Then the number midpoint = n-1!
    #-----

    #Finally, we use the 'closest_val' function above, to quantize all the values here:
    X_quant = []
    for i in white_matter_df['X Coordinate']:
        X_quant.append(closest_val(midpoints, i))
        
    white_matter_df['X_quant'] = X_quant
    
    Y_quant = []
    for i in white_matter_df['Y Coordinate']:
        Y_quant.append(closest_val(midpoints, i))

    white_matter_df['Y_quant'] = Y_quant
    
    return(max_val, lim, midpoints, white_matter_df)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #c47f4844-0b1d-43fa-b183-f9abe07b60ca
def make_white_matter_df (input_df, mkr='+', q_factor = 100, bin_thresh=None):

    #Apply the dimensionality reduction technique
    white_matter_df = pca_transform(input_df)
    
    #In case the index is duplicated.
    if 'Unnamed: 0' in white_matter_df.columns:
        white_matter_df = white_matter_df.drop('Unnamed: 0', axis=1)

    #--------------
    #Quantized by whatever factor the user provides.
    # white_matter_df['X_quant'] = round(white_matter_df['X Coordinate']/q_factor)*q_factor
    # white_matter_df['Y_quant'] = round(white_matter_df['Y Coordinate']/q_factor)*q_factor

    max_val, lim, midpoints, white_matter_df = make_quant(white_matter_df, q_factor=q_factor)
    #--------------

    #This makes a new dataframe of just the quantized positions, which  should be much smaller than the original.
    #It will sum together the marker expression for these points.
    #https://stackoverflow.com/questions/38985053/groupby-and-sum-only-one-column
    exp_bin_df = white_matter_df.groupby(['X_quant','Y_quant'], as_index=False)['Marker'].sum()
    exp_bin_df  

    #Now to convert marker to binary based on the mean expression.

    #--First, we scale the expression of the marker column by mean expression for all quantized positions.
    #--This makes the resulting graph easier to interpret.
    mn = statistics.mean(exp_bin_df['Marker'].values)
    # print('mn is:', mn)
    
    exp_bin_df['Marker'] = exp_bin_df['Marker']/mn
    # print('exp_bin_df is:', exp_bin_df.head())

    #Helpful to have in a list format
    exp = exp_bin_df['Marker'].values
    # print('exp is:', exp[:5])

    #--And then, we deploy *Otsu's Method* to determine an appropriate cutoff value for binarization:
    # https://en.wikipedia.org/wiki/Otsu%27s_method
    # Code is adapted from: https://docs.opencv.org/3.4/d7/d4d/tutorial_py_thresholding.html

    #values must be scaled from 0-255 for uint8 format, which is what cv2 requires.
    m_kr = exp/exp.max()*255
    # print('m_kr is:', m_kr[:5])
    
    #we preserve this scale factor because we're going to neeed it later...
    factor = exp.max()/255
    # print("Scale factor is:", factor)
    
    #Convert to a list
     #(Already did that...)

    #Convert to numpy array
    matr = np.array(m_kr)
    # print('matr is:', matr[:5])
    
    #Now convert to uint8 format
    matr = matr.astype(np.uint8)
    # print('matr is:', matr[:5])

    #And now we can apply cv2's histogram generating function.
    hist = cv.calcHist([matr],[0],None,[256],[0,256])
    
    #Apply Otsu's method to the newly generated histogram:
    hist_norm = hist.ravel()/hist.sum()
    Q = hist_norm.cumsum()
    bins = np.arange(256)
    fn_min = np.inf
    thresh = -1
    for i in range(1,256):
        p1,p2 = np.hsplit(hist_norm,[i]) # probabilities
        q1,q2 = Q[i],Q[255]-Q[i] # cum sum of classes
        if q1 < 1.e-6 or q2 < 1.e-6:
            continue
        b1,b2 = np.hsplit(bins,[i]) # weights
        # finding means and variances
        m1,m2 = np.sum(p1*b1)/q1, np.sum(p2*b2)/q2
        v1,v2 = np.sum(((b1-m1)**2)*p1)/q1,np.sum(((b2-m2)**2)*p2)/q2
        # calculates the minimization function
        fn = v1*q1 + v2*q2
        if fn < fn_min:
            fn_min = fn
            thresh = i

    print()

    #Finally, we take "thresh", which is our threshold on the 0-255 scale, and reconstitute it with our scale factor:
    otsu_threshold = thresh*factor
    print("Via Otsu's Method for bimodal distributions, we binarize expression at x", round(otsu_threshold, 3), "of the mean expression value.")

    # ----------
    # And if the user has not specified a value for 'bin_thresh', then we use this value generated by Otsu's method:
    if bin_thresh == None:
        bin_thresh = otsu_threshold
    # ----------

    #And we make the new column accordingly:
    # -------
    # Using 'bin_thresh' rather than 'otsu_threshold'
    # -------
    
    #Recall that if our marker is negative, the coding scheme is flipped. 
    if mkr == '+' :
      exp_bin_df['Binarized_Marker'] = np.where(exp_bin_df['Marker'] > bin_thresh, 1, 0)  
    #Because a negative marker says: "This is not an oligodendrocyte." eg. Slc17a6
    elif mkr == '-' :
      exp_bin_df['Binarized_Marker'] = np.where(exp_bin_df['Marker'] > bin_thresh, 0, 1) 
    else:
      print("INVALID MARKER! Must be either '+' or '-'.")

    #We duplicate this column just prior to the merge, so that it's also copied to the 'white_matter_df' table.
    #Just for clarity, we'll leave it in the original table as well.
    exp_bin_df['Position_ID'] = exp_bin_df.index

    #Finally, we add the binarized expression value back to the original dataframe.
    white_matter_df = pd.merge(white_matter_df, exp_bin_df, how="right", on=["X_quant", "Y_quant"])
    white_matter_df = white_matter_df.drop(columns={'Marker_y'})
    white_matter_df = white_matter_df.rename({'Marker_x':'Marker'}, axis=1)
    white_matter_df
    
    print()
    print("Note: The argument 'q_factor' is used to bin points together. Points which share the same 'X_quant' and 'Y_Quant' will have their expression of the marker summed together for that particular position, 'Position_ID'. Binarized expression is calculated for each position. The fewer positions, the less time the annotation process will take.")

    
    #Potentially useful in deciding whether to adjust 'q_factor':
    X_set = set(white_matter_df['X_quant'].values)
    Y_set = set(white_matter_df['Y_quant'].values)
    
    print()
    print('q_factor=', q_factor,', Maximum number of quantized positions= ', len(X_set)*len(Y_set),',', len(X_set), 'x', len(Y_set))

    print('Actual number of quantized positions:',len(exp_bin_df.index))

    return (white_matter_df, exp_bin_df, otsu_threshold, bin_thresh)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #2a6a1ab5-ed82-40db-912c-f08d51428ea4
def neighbors(focus, df, rad=100):

  #"Cutting out" a square search region to reduce the time the algorithm takes.
  #This filters for all points within the given radius in either the X or Y axis, producing a square "cut-out"

  X = df.iloc[focus]['X_quant']
  Y = df.iloc[focus]['Y_quant']

  df_filt = df[(df['X_quant']>(X-rad)) & (df['X_quant']<(X+rad))]
  df_filt = df_filt[(df_filt['Y_quant']>(Y-rad)) & (df_filt['Y_quant']<(Y+rad))]

  #Filter for points which meet the radius requirement, and simply output their IDs.
  #Recall that we want a circular region around the given point.

  n_list = []
    
  for i in df_filt.values:
    # print (i[0], i[1], i[4])    

    i = list(i)
    X_ = float(i[0])
    Y_ = float(i[1])
      
    dist = (X-X_)**2 + (Y-Y_)**2
    if dist <= rad**2:
      #These are indicies in the dataframe. Must be integer.
      n_list.append(int(i[4]))

  return n_list

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #0e838509-6646-4356-b8c8-c970bcb660ff
def mk_outline(df, q_factor):

    #Label all existing points as 1
    df['Smooth_Mask'] = 1
    
    z='Smooth_Mask'
    fill=0
    # q_factor=100
    
    # 1. Start by filling in the background.
    area = max(max(df['X_quant']), max(df['Y_quant'])) + q_factor/2
    
    # Create a blank dataframe with all possible quantized positions,
    matr = []
    r = int(area/q_factor)
    
    for i in range (0, r+1):
      for j in range (0, r+1):
          matr.append([float((i+0.5)*q_factor), float((j+0.5)*q_factor)])
    
    matr = pd.DataFrame(matr, columns = ['X_quant', 'Y_quant'])
    
    # And merge it with our existing dataframe:
    matr = pd.merge(matr, df, on=['X_quant', 'Y_quant'], how='left')
    #And let's fill in blank positions in the mask with a defined value.
    #Except that for the first figure, it's better to leave it as-is/
    if fill=='blank':
        pass
    else:
        matr[z] = matr[z].fillna(fill).astype(int)
    
    #2. Convert to pivot table.
    pivot_table = matr.pivot(index='Y_quant', columns='X_quant', values=z)
    #Note that the columns seem backwards here, but that's necessary for it to render the way we want it to.
    
    #And convert to Numpy array:
    pivot_table = np.array(pivot_table)

    return(pivot_table, matr)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #d949de1b-ba74-4c58-9964-41350f602fb8
def blur_smooth(pivot_table):
    #Make the vector of zeroes.
    n = pivot_table.shape[0]
    #n_arr = np.zeros((n, 1), dtype=int)
    n_arr = np.zeros((n), dtype=int)
    
    n_arr = n_arr.reshape(1, n)
    n_arr_2d = n_arr.reshape(n, 1)

    #And now we apply the 8 transformations:
    pivot_table_1_0 = np.concatenate([n_arr, pivot_table[0:-1, :]], axis=0)
    pivot_table_m1_0 = np.concatenate([pivot_table[1:, :], n_arr], axis=0)
    pivot_table_0_1 = np.concatenate([n_arr_2d, pivot_table[:, 0:-1]], axis=1)
    pivot_table_0_m1 = np.concatenate([pivot_table[:, 1:], n_arr_2d], axis=1)
    
    pivot_table_1_1 = np.concatenate([n_arr, pivot_table_0_1[0:-1, :]], axis=0)
    pivot_table_m1_1 = np.concatenate([pivot_table_0_1[1:, :], n_arr], axis=0)
    pivot_table_1_m1 = np.concatenate([n_arr, pivot_table_0_m1[0:-1, :]], axis=0)
    pivot_table_m1_m1 = np.concatenate([pivot_table_0_m1[1:, :], n_arr], axis=0)

    #Stack these matricies and sum across this new dimension:
    pivot_matrix = np.stack([pivot_table_1_0, pivot_table_m1_0, pivot_table_0_1, pivot_table_0_m1, 
                             pivot_table_1_1, pivot_table_1_m1, pivot_table_m1_1, pivot_table_m1_m1], axis=0)

    pivot_sum = np.sum(pivot_matrix, axis=0)

    #The aim is to filter out "1"  points with fewer than 3 "1" neighbours.
    #1. We start by making the binary filter layer
    pivot_sum_bin = (pivot_sum > 2)*1
    #2. And apply it:
    result = pivot_sum_bin*pivot_table

    diffs = np.sum(result != pivot_table)
    print('flip count:', diffs)
    
    return (result, diffs)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #728d1039-9e50-4d66-bd62-85132ca6ee26
def iter_smooth(df, raw_df, q_factor):
    #Convert dataframe into a 2D numpy array for faster processing.
    pivot_table, matr = mk_outline(df, q_factor)

    #Iteratively apply the "blur_smooth" function
    diffs = 1 # --To start the loop.
    count = 0
    
    while diffs != 0 & count<20:
        result, diffs = blur_smooth(pivot_table)
        #Update for the next iteration of the loop.
        pivot_table =result

    #Reflect the final matrix result in the X-Y axis
    result = result.T

    #Start building up the column to replace the current 'Smooth_Mask' column
    #This column shows whether a point should be allowed to remain in 'exp_bin_df'
    mask = []
    for i in result:
      for j in i:
        mask.append(j)

    #Update the column
    matr['Smooth_Mask'] = mask

    # --Recall from the previous version of this function:
    # We filter out any points in 'white_matter_df' corresponding to dropped positions.
    # So that there are no points in that df corresponding to positions that no longer exist.
    
    #Let's make a list of all the points for which 'Mask' = 0. We'll want to filter 'white_matter_df' for these points.
    matr_dropped = list(matr[matr['Smooth_Mask'] == 0]['Position_ID'])

    #And let's filter these positions out of 'white_matter_df'. Note that in this table, 'Position_ID' is NOT the index.
    raw_df = raw_df[~raw_df['Position_ID'].isin(matr_dropped)]
    
    #And now we drop all points which are labelled as '0' in the mask.
    matr = matr[matr['Smooth_Mask'] == 1]
    #And we drop this column, since we no longer need it:
    matr = matr.drop(columns=['Smooth_Mask'])

    #Return the newly filtered version of 'exp_bin_df'
    df = matr.copy()
    
    return (df, raw_df)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #55659f5a-065a-4559-ad19-78fda8757b7e
def mk_outline_2(df, q_factor):

    #Load in our initial assumption as to which points are part of the mask.
    df['Mask'] = df['Binarized_Marker']
    
    z='Mask'
    # fill=0
    # q_factor=100
    
    # 1. Start by filling in the background.
    area = max(max(df['X_quant']), max(df['Y_quant'])) + q_factor/2
    
    # Create a blank dataframe with all possible quantized positions,
    matr = []
    r = int(area/q_factor)
    
    for i in range (0, r+1):
      for j in range (0, r+1):
          matr.append([float((i+0.5)*q_factor), float((j+0.5)*q_factor)])
    
    matr = pd.DataFrame(matr, columns = ['X_quant', 'Y_quant'])
    
    # And merge it with our existing dataframe:
    matr = pd.merge(matr, df, on=['X_quant', 'Y_quant'], how='left')
    #And let's fill in blank positions in the mask with a defined value.
    #Except that for the first figure, it's better to leave it as-is/
    
    # if fill=='blank':
    #     pass
    # else:
    #     matr[z] = matr[z].fillna(fill).astype(int)
    
    #2. Convert to pivot table.
    pivot_table = matr.pivot(index='Y_quant', columns='X_quant', values=z)
    #Note that the columns seem backwards here, but that's necessary for it to render the way we want it to.
    
    #And convert to Numpy array:
    pivot_table = np.array(pivot_table)

    return(pivot_table, matr)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #e454a2ad-d499-426b-aef4-9df12e00506d
import warnings

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #99bb6aa9-48b9-4ce3-9fe7-7a7bf1c5cf3f
def blur_smooth_2(pivot_table):
    #Make the vector of zeroes.
    n = pivot_table.shape[0]

    # --------------------
    #Making the vectors we're going to use to "shift" the matrix.
    n_arr = [math.nan] * n
    n_arr = np.array(n_arr)
    #---------------------
    
    n_arr = n_arr.reshape(1, n)
    n_arr_2d = n_arr.reshape(n, 1)

    #And now we apply the 8 transformations:
    pivot_table_1_0 = np.concatenate([n_arr, pivot_table[0:-1, :]], axis=0)
    pivot_table_m1_0 = np.concatenate([pivot_table[1:, :], n_arr], axis=0)
    pivot_table_0_1 = np.concatenate([n_arr_2d, pivot_table[:, 0:-1]], axis=1)
    pivot_table_0_m1 = np.concatenate([pivot_table[:, 1:], n_arr_2d], axis=1)
    
    pivot_table_1_1 = np.concatenate([n_arr, pivot_table_0_1[0:-1, :]], axis=0)
    pivot_table_m1_1 = np.concatenate([pivot_table_0_1[1:, :], n_arr], axis=0)
    pivot_table_1_m1 = np.concatenate([n_arr, pivot_table_0_m1[0:-1, :]], axis=0)
    pivot_table_m1_m1 = np.concatenate([pivot_table_0_m1[1:, :], n_arr], axis=0)

    #Stack these matricies and sum across this new dimension:
    pivot_matrix = np.stack([pivot_table_1_0, pivot_table_m1_0, pivot_table_0_1, pivot_table_0_m1, 
                             pivot_table_1_1, pivot_table_1_m1, pivot_table_m1_1, pivot_table_m1_m1], axis=0)

    pivot_sum = np.sum(pivot_matrix, axis=0)
    #Note: We use 'nanmean' instead of 'average' because we want the 'nan' values to be ignored when calculating the mean expression.
    with warnings.catch_warnings(action="ignore"): # --Supresses the warning we get when an empty slice is encountered.
        pivot_avg = np.nanmean(pivot_matrix, axis=0)
    # pivot_avg = np.average(pivot_matrix, axis=0)

    #The aim is to filter out "1"  points with fewer than 3 "1" neighbours.
    #1. We start by making the binary filter layer
    # pivot_sum_bin = (pivot_sum > 2)*1
    #2. And apply it:
    # result = pivot_sum_bin*pivot_table

    # result = pivot_sum
    result = pivot_avg
    
    return (result, pivot_matrix)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #4cc75eb6-28cd-4903-8ff4-ce2eefbd33b2
def solidify(pivot_table):

    #Since we need to remake these objects everytime we run this function,
    # it makes sense to nest this function into 'solidify':
    result, pivot_matrix = blur_smooth_2(pivot_table)
    
    # 1. If a point has fewer that 3 neighbours, we automatically impute it as zero.
    nan_matrix = np.isnan(pivot_matrix).sum(axis=0)
    nan_matrix_bin = 1-(nan_matrix > 5)*1
    # 2. If a point is "0", and averages greater than "5/8" in its immediate neighbourhod, we flip it to "1".
    inv_pivot = 1 - pivot_table
    zero_layer = inv_pivot*((result >= (5/8))*1)
    # 3. If a point is "1", and averages greater than 7/8 zeroes in its immediate neighbourhood, we flip it to 0.
    inv_result = 1 - result
    one_layer = pivot_table*((inv_result >= (7/8))*1)

    #Finally, we apply all three layers and return the result:
    pivot_table_new = pivot_table*nan_matrix_bin + zero_layer - one_layer

    #-------------------- Edit: 2.27.26
    pivot_table_new = abs(pivot_table_new)
    #--------------------
    
    #This method only works on matricies of integers.
    #Which is a problem, because 'nan' is technically a float value.;=
    with warnings.catch_warnings(action="ignore"): # --We also need it to ignore the nans, and not give use an annoying warning everytime.
        diffs = np.sum(pivot_table_new.astype(int) != pivot_table.astype(int))
    print('flip count:', diffs)

    return (pivot_table_new, diffs)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #d95dfc8e-8b89-4c58-8261-cd9fc9893572
def infill_mask(df, q_factor):
    pivot_table, matr = mk_outline_2(df, q_factor)
    #Recall that 'solidify' now contains 'blur_smooth_2'
    diffs = 1
    count = 0
    max_iterations = 20
    
    #Iteratively apply the function to solidify the outline of the target region
    while diffs != 0 and count < max_iterations:  #--Edit: 2.27.26 
        #('and' is not the same as "&"! This causes the loop to ignore the second condition and run forever!!!)
        pivot_table_new, diffs = solidify(pivot_table)
        #Update for the next iteration of the loop.
        pivot_table = pivot_table_new
        count += 1
        #----------------------------------------------
        #Outputs a plot of each step, so we can visualize progress and identify bugs.
        # plt.imshow(pivot_table, origin="lower", interpolation='nearest')
        # plt.colorbar()
        # plt.show()
        #----------------------------------------------
    
    #Reflect the final matrix result in the X-Y axis
    pivot_table = pivot_table.T
    
    #Start building up the column to replace the current 'Smooth_Mask' column
    #This column shows whether a point should be allowed to remain in 'exp_bin_df'
    mask = []
    for i in pivot_table:
      for j in i:
        mask.append(j)
    
    #Update the column
    matr['Mask'] = mask  

    #Finally, we merge the new values (and return the object):
    output = df[['X_quant', 'Y_quant', 'Marker', 'Binarized_Marker', 'Position_ID']].merge(
        matr[['X_quant', 'Y_quant', 'Mask']], on=['X_quant', 'Y_quant'], how='left')

    #Update the value of df (Redundant, yes. But I like to be clear about the flow of logic here.
    df = output.copy()
    
    return (df)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #addb325d-ff41-4b85-ab7f-de782f85c453
def get_midpoints(df, q_factor_s):
    #Determine the range along which we need to quantize.
    max_val = max(max(df['X_quant']),max(df['Y_quant']))
    #We set the limit of the range to be greater than the maximum possible value in either axis, and add one more interval just in-case it rounds down.
    lim = round(max_val/q_factor_s)*q_factor_s + q_factor_s
    #Create list of possible values. Not inclusive of the top-most value.
    vals = list(range(0, lim, q_factor_s))
    #And, we output the midpoint pf each range,
    midpoints = [item + (q_factor_s/2) for item in vals]
    #-----
    # This is very important. If the number possible quantized points along a range = n,
    # Then the number midpoint = n-1!
    #-----
    
    return(midpoints)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #092b48f9-5f13-4f92-983f-99dbd348e2c4
def make_scaled_df(df, q_factor, scale):
    
    q_factor_s = q_factor*scale
    
    #MUST make a copy of 'df', otherwise all these changes will be commuted back to the original object.
    df_ = df.copy()
    
    #Quantized by whatever factor the user provides.
    # df_['X_quant'] = round(df_['X_quant']/q_factor_s)*q_factor_s
    # df_['Y_quant'] = round(df_['Y_quant']/q_factor_s)*q_factor_s

    # ---------------------------------------------------------
    midpoints = get_midpoints(df, q_factor_s)

    #And as usual, we are required to build this up as a vector:
    X_vals = []
    for i in df_['X_quant']:
        X_vals.append(closest_val(midpoints, i))
        
    Y_vals = []
    for i in df_['Y_quant']:
        Y_vals.append(closest_val(midpoints, i))
    
    df_['X_quant'] = X_vals
    df_['Y_quant'] = Y_vals
    # ----------------------------------------------------------

    #And collapse the dataframe based on these values.
    df_out = df_.groupby(['X_quant','Y_quant'], as_index=False)['Mask'].sum()

    #Re-binarize so that all points with non-zero expression are labelled "1":
    df_out['Bin_Mask'] = np.where(df_out['Mask'] > 0, 1, 0)
    #And to avoid confusion, let's make the format of this dataframe make sense. Firstly, let's rename 'Mask' to 'Marker'
    df_out['Marker'] = df_out['Mask']
    #The column of binarized expression needs to be called 'Binarized_Marker', as this is what the infill function is looking for.
    df_out['Binarized_Marker'] = df_out['Bin_Mask']
    #Delete the duplicate columns.
    df_out = df_out.drop(columns=['Mask','Bin_Mask'])
    #We also need to output our indicies to the 5th(4-indexed) column, or 'infill_mask' will throw an error.
    df_out['Position_ID'] = df_out.index

    #And now we trim the original-length dataframe (with now inaccurate positions) into a correspondence table.
    df_ = df_[['X_quant', 'Y_quant']]
    #And let's add the idex in the new table that corresponds to a particular position.
    # index_df = df_out[['X_quant', 'Y_quant']]
    index_df = df_out[['X_quant', 'Y_quant']].copy() #--- Hopefully this gets rid of the annoying warning.
    index_df['Index'] = index_df.index
    #merge onto df, to add indicies.
    df_ = pd.merge(df_, index_df, on=['X_quant', 'Y_quant'], how='left')
    #We now drop the (quantized) X and Y positions from 'df_', given that these are not accurate to the
    #high resolution points. So, they'll only cause confusion...
    df_ = df_[['Index']]

    return (df_, df_out)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #038c0642-9538-43e9-85ed-41fe08817864
def infill_mask_complex(exp_bin_df, q_factor, scale=2):

    print("Applying high-resolution infill mask: ")
    #We start off by applying the infill mask to the higher resolution dataset
    high_res_mask_df = infill_mask(exp_bin_df, q_factor)

    #If the user enters a single number, then we'll need to convert it to a list in order for the iterable to work:
    if type(scale)==int or type(scale)==float:
        scale_lis = []
        scale_lis.append(scale)
        
        scale = scale_lis

    #We'll also need to rationalize the output of 'relief' if generating it multiple times.
    #To achieve this: We start with a blank object in which we label everything as 'unaffected'.
    lis_1 = ['Unaffected']*len(exp_bin_df)
    lis_1 = pd.DataFrame(lis_1)
    #This first column in the dataframe will be labeled 'lis_1[0]'. This is what we'll compare our
    #relief mak to, everytime it's generated.

    for scale_n in scale:
        
        #We then make a new version of this quantized and masked dataframe, using the 'q_factor' provided and the 'scale' provided.
        #The table we call 'indicies' is what maps this low-res dataframe onto the high-res one.
        indicies, low_res_df = make_scaled_df(high_res_mask_df, q_factor, scale_n)
    
        print("Applying low-resolution filter mask: ")
        #Apply the function 'infill_mask' to this new lower resolution dataframe, to remove floating points/clusters.
        qf = q_factor #recall we must provide an accurate distance between points for this function.
        low_res_df = infill_mask(low_res_df, q_factor = (qf*scale_n))
    
        #And now we set about merging the two masks and outputing the results:
    
        #We need to make an index column to merge on.
        low_res_df['Index'] =low_res_df.index
        #And merge only the columns we care about
        indicies = pd.merge(indicies, low_res_df[['Mask','Index']], on=['Index'], how='left')
        #Ensure that 'Mask' is an integer column.
        indicies['Mask'] = indicies['Mask'].astype(int)
    
        #Now that we have our indicies, we can apply the new mask back to the higher resolution data. 
        conflict_df = pd.merge(high_res_mask_df, indicies[['Mask']], left_index=True, right_index=True, how='inner')
        #Finally, we rationalize the two masks, by taking their overlap.
        conflict_df['Mask'] = np.where((conflict_df['Mask_x'] == 1) & (conflict_df['Mask_y'] == 1), 1, 0)
    
        #Use seaborn to display to the user which points have been retained/removed, so they can adjust as needed.
        conditions = [
            (conflict_df['Mask'] == 1),
            (conflict_df['Mask_x'] == 1) & (conflict_df['Mask'] == 0),
            (conflict_df['Mask_x'] == 0) & (conflict_df['Mask'] == 0)
        ]
        
        values = ['Retained', 'Removed', 'Unaffected']
        
        # Apply conditions to create a new column:
        conflict_df['Relief'] = np.select(conditions, values)
    
        #Instead of making the plot within this function, we output 'Relief' as a second object, so that we can plot it using the same parameters as all our other graphs in 'wm_annot'.
        relief = conflict_df['Relief']
        
        #And let's drop the conflicting 'Mask' columns, now that we no longer need them.
        conflict_df = conflict_df.drop(columns=['Mask_x', 'Mask_y', 'Relief'])

        #------------------------------------------------------------------------------
        #And now we compare this 'relief' list to the current version that we have saved.

        #Add it to the dataframe:
        lis_1[1] = relief

        #And our conditions are to remove any points removed in by our new mask.
        conditions = [
            (lis_1[0] == 'Unaffected') & (lis_1[1] == 'Unaffected'),
            (lis_1[0] == 'Unaffected') & (lis_1[1] == 'Retained'), #Only apllicable on the first run..
            (lis_1[0] == 'Unaffected') & (lis_1[1] == 'Removed'), #...when the reference is blank.
            #Only points retained across masks should remain.
            (lis_1[0] == 'Retained') & (lis_1[1] == 'Retained'),
            #All others should be filtered out.
            (lis_1[0] == 'Retained') & (lis_1[1] == 'Removed'),
            (lis_1[0] == 'Removed') & (lis_1[1] == 'Retained'),
            (lis_1[0] == 'Removed') & (lis_1[1] == 'Removed')
        ]
        
        values = ['Unaffected', 'Retained', 'Removed',  'Retained', 'Removed','Removed', 'Removed']
        
        # Apply conditions to create a new column:
        lis_1['Relief'] = np.select(conditions, values)

        #Return the latest version of 'relief' to the user:
        relief = lis_1['Relief']
        #And, reset our dataframe in case we need it again:
        lis_1 = pd.DataFrame(lis_1['Relief'])
        lis_1 = lis_1.rename(columns={'Relief': 0})
        #-----------------------------------------------------------------------------

    #And to be sure we've filtered out all the points that need to be removed from our final output dataframe:
    #This line suppresses the warning we might get due to the boolean.
    pd.set_option("future.no_silent_downcasting", True)
    lis_1['Bool'] = lis_1[0]=='Removed'
    lis_1['Bool'] = lis_1['Bool'].replace({True: 0, False: 1})
    #Notice we've inverted this, so that 'Remove' values are all coded as zero. Anything else is one.
    conflict_df['Mask'] = conflict_df['Mask']*lis_1['Bool']
    #And now any "1" value in our mask that is to be removed is multiplied by zero, removing it.

    #But now, we need to be absolutely sure that the resulting column is *numeric* datatype. Not *object*! Or it will break something downstream.
    # Step 1: Convert to numeric safely
    conflict_df['Mask'] = pd.to_numeric(conflict_df['Mask'], errors='coerce')  # Non-numeric -> NaN
    # Step 2: Convert to integer
    conflict_df['Mask'] = conflict_df['Mask'].astype(int)  # Pandas nullable integer type

    #And return the final mask.
    return (conflict_df, relief)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #1c326734-2ac9-4b14-8600-56247ce1329e
from sklearn.neighbors import NearestNeighbors

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #ad89aadd-95c3-4f41-af9e-e381a4d3b922
def d_scale(df, K = 3, power=2):

    #As usual, to prevent these edits from being transmitted back to the original object:
    df_ = df.copy()

    # 2. Calculate k-NN density metric (Distance to the Kth nearest neighbor)
    # Density is INVERSELY proportional to this distance (r_k).
    # We fit the model and find the distance to the Kth neighbor (k=K).
    nn = NearestNeighbors(n_neighbors=K).fit(df_.iloc[:, [0,1]])
    
    # The output is (distances, indices). We only need the distances.
    # distances[:, K-1] is the distance to the Kth nearest neighbor (since distances are sorted).
    distances, indices = nn.kneighbors(df_.iloc[:, [0,1]])
    df_['kth_neighbor_distance'] = distances[:, K-1]
        
    #Average values across this 'density' column:
    #We also include this 'power' scaling factor, which we can fine-tune later.
    dist = (statistics.mean(df_['kth_neighbor_distance']))

    #To make a long story short, I've decided to manually set these, because the math is really confusing:
    if dist<20:
        d_scale = 5
    elif dist<60:
        d_scale = 10
    elif dist<80:
        d_scale = 15
    elif dist<120:
        d_scale = 20
    elif dist<160:
        d_scale = 40
    elif dist<250:
        d_scale = 60
    elif dist<400:
        d_scale = 80
    else:
        d_scale = 100

    # print(df)
    # print(round(statistics.mean(df['kth_neighbor_distance']), 3), round(d_scale, 3))
    
    return(d_scale)
#--------------------------------------------

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #26e0560b-1bc1-4c04-bd27-5add9568128f
def mk_tile_plot (df, q_factor, theme='viridis', title_message='[your_title_here]'):
    # 1. Start by filling in the background.
    area = max(max(exp_bin_df['X_quant']), max(exp_bin_df['Y_quant'])) + q_factor/2

    # Create a blank dataframe with all possible quantized positions,
    matr = []
    r = int(area/q_factor)

    # ---
    # Recall that we need the midpoint of each range. Hence, the complicated math...
    # ---
    for i in range (0, r+1):
      for j in range (0, r+1):
          matr.append([float((i+0.5)*q_factor), float((j+0.5)*q_factor)])

    #Convert to dataframe:
    matr = pd.DataFrame(matr, columns = ['X_quant', 'Y_quant'])
    
    # And merge it with our existing dataframe, filling in any missing points as "2" (background).
    matr = pd.merge(matr, exp_bin_df, on=['X_quant', 'Y_quant'], how='left')
    #And let's fill in blank positions in the mask.
    matr['Mask'] = matr['Mask'].fillna(2).astype(int)  

    #2. Convert to pivot table.
    pivot_table = matr.pivot(index='Y_quant', columns='X_quant', values='Mask')
    #Note that the columns seem backwards here, but that's necessary for it to render the way we want it to.

    # 3. Create the Heatmap (Tile Plot)
    plt.figure(figsize=(8, 6))
    ax = sns.heatmap(
        pivot_table,
        cmap=theme, # Colormap to use (e.g., 'viridis', 'coolwarm', 'YlGnBu')
        cbar=False,      # Show the color bar (legend for the third variable)
        linewidths=.5,  # Space between tiles
        linecolor='white',
        alpha=0.6
    )
    
    #Set limits to correspond to our actual data:
    ax.set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
    ax.set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
  
    # Set the title and labels
    plt.title(title_message)
    
    plt.show()


# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #3d2c1c6c-6297-4a3f-b506-422cfdf26013
def mk_pivot (df, q_factor, z='Mask', fill='blank'):
    # 1. Start by filling in the background.
    area = max(max(df['X_quant']), max(df['Y_quant'])) + q_factor/2

    # Create a blank dataframe with all possible quantized positions,
    matr = []
    r = int(area/q_factor)

    for i in range (0, r+1):
      for j in range (0, r+1):
          matr.append([float((i+0.5)*q_factor), float((j+0.5)*q_factor)])
    
    matr = pd.DataFrame(matr, columns = ['X_quant', 'Y_quant'])
    
    # And merge it with our existing dataframe:
    matr = pd.merge(matr, df, on=['X_quant', 'Y_quant'], how='left')
    #And let's fill in blank positions in the mask with a defined value.
    #Except that for the first figure, it's better to leave it as-is/
    if fill=='blank':
        pass
    else:
        matr[z] = matr[z].fillna(fill).astype(int)

    #2. Convert to pivot table.
    pivot_table = matr.pivot(index='Y_quant', columns='X_quant', values=z)
    #Note that the columns seem backwards here, but that's necessary for it to render the way we want it to.

    return(pivot_table)


# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #fd858af3-2982-41b3-b4cc-be278dcb0c9a
def wm_annot(input_df, mkr='+', q_factor=100, bin_thresh=None, smooth=False, solver='infill', scale=2, fig_path=None):

    #Intermeditate variables:
    marker = mkr
    quant_factor = q_factor
    binarization_threshold = bin_thresh
    scaling_factor = scale

    #We start by generating the required dataframe objects. Recall that 'pca_transform' is already buried within this function.
    white_matter_df, exp_bin_df, otsu_threshold, bin_thresh = make_white_matter_df(input_df, mkr=marker, bin_thresh = binarization_threshold, q_factor=quant_factor)
    
    # Create a 2x2 grid of subplots
    fig, axes = plt.subplots(2, 2, figsize=(12, 12))

    #Adapt sizes of lines to the q_factor.
    #lines = ((q_factor/100)*.1)
    lines = 0
    
    #Print the dataframe of raw positions:
    sns.scatterplot(data=white_matter_df, x='X Coordinate', y='Y Coordinate', hue='Marker', s=(d_scale(white_matter_df)), ax=axes[0,0])
    axes[0,0].set_title("Scatterplot of Raw Positions")

    #Print the dataframe of quantized positions:
    #sns.scatterplot(data=exp_bin_df, x='X_quant', y='Y_quant', hue='Marker', s=(d_scale(exp_bin_df)), ax=axes[0,1])
    #axes[0,1].set_title("Scatterplot of Binned and Scaled Positions")
    
    pivot_table = mk_pivot(exp_bin_df, q_factor=quant_factor, z='Marker', fill='blank')
    sns.heatmap(pivot_table, cmap='magma', cbar=False, linewidths=lines, linecolor='white', alpha=0.8, ax=axes[0,1])
    axes[0,1].set_title("Scatterplot of Binned and Scaled Positions")
    axes[0,1].set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
    axes[0,1].set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
    axes[0,1].collections[0].cmap.set_bad('w') #Setting a white background here.
    
    #Print the binarized positions:
    #sns.scatterplot(data=exp_bin_df, x='X_quant', y='Y_quant', hue='Binarized_Marker', ax=axes[1,0], s=(d_scale(exp_bin_df)))
    #axes[1,0].set_title("Scatterplot of Binarized Positions")

    pivot_table = mk_pivot(exp_bin_df, q_factor=quant_factor, z='Binarized_Marker', fill=2)
    sns.heatmap(pivot_table, cmap='viridis', cbar=False, linewidths=lines, linecolor='white', alpha=0.8, ax=axes[1,0])
    axes[1,0].set_title("Scatterplot of Binarized Positions")
    axes[1,0].set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
    axes[1,0].set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
    # axes[1,0].collections[0].cmap.set_bad('w')  --Here' we use viridis which gives a yellow background

    #Print the otsu's graph:
    sns.histplot(exp_bin_df['Marker'], bins=256, kde=True, ax=axes[1,1])
    plt.axvline(x=(otsu_threshold), color='green', linestyle='--', linewidth=1)
    plt.axvline(x=(bin_thresh), color='red', linestyle='--', linewidth=1)
    axes[1,1].set_title("Histogram of Marker Expression")
    
    # Adjust layout for better spacing
    plt.tight_layout()

    #Output the  figure if user has provided a path to do so:
    if fig_path != None:
        fig.savefig(fig_path+'Binarization.png', dpi=300)

    # Show the plots
    plt.show()

    #And to "solidify" the mask, we fit one of our two solvers to the dataset. So far though, we only have 'infill'.
    if solver =='infill':
        print()
        print("Applying infill method:")
        print()  
        #exp_bin_df = infill_mask(exp_bin_df, q_factor = quant_factor)
        exp_bin_df, relief = infill_mask_complex(exp_bin_df, q_factor = quant_factor, scale=scaling_factor)
        print()

        #Visualize the relief object, so the user can decide whether they want to adjust some parameters.

        # Create a 1x1 grid of subplots
        fig, axes = plt.subplots(1, 1, figsize=(6, 6))
        
        #Print the dataframe of raw positions:
        #sns.scatterplot(exp_bin_df, x='X_quant', y='Y_quant', hue=relief, palette={"Retained": "#45B7D1", "Unaffected":"#D3D3D3", "Removed": "#FF6B6B"}, s=(d_scale(exp_bin_df)), ax=axes) #ax=axes[0])
        #axes.set_title("Results of Complex Infill Mask:")

        #Make a copy of the table and add 'retained' back to it:
        exp_bin_df__ = exp_bin_df.copy()
        exp_bin_df__['Relief'] = relief
        #Our pivot table will refuse to display non-numerical values, hence why we are required to go through the trouble of converting everything back.
        conditions = [
            (exp_bin_df__['Relief'] == 'Retained'),
            (exp_bin_df__['Relief'] == 'Removed'),
            (exp_bin_df__['Relief'] == 'Unaffected')
        ]
        
        values = [1, 2, 0]
        
        # Apply conditions to create a new column:
        exp_bin_df__['Relief_num'] = np.select(conditions, values)

        # print(exp_bin_df__)

        pivot_table = mk_pivot(exp_bin_df__, q_factor=quant_factor, z='Relief_num', fill='blank')
        sns.heatmap(pivot_table, cmap='coolwarm', cbar=False, linewidths=lines, linecolor='white', alpha=0.5, ax=axes)
        axes.set_title("Results of Complex Infill Mask:")
        axes.set_xlim(0, (max(exp_bin_df__['X_quant'])/q_factor)+1)
        axes.set_ylim(0, (max(exp_bin_df__['Y_quant'])/q_factor)+1)
        # axes.collections[0].cmap.set_bad('w')  --Here' we use viridis which gives a yellow background
        
        # Adjust layout for better spacing
        plt.tight_layout()

        if fig_path != None:
            fig.savefig(fig_path+'Infill.png', dpi=300)
    
        # Show the plots
        plt.show()
    
        print()
        print("Points labelled as 'Removed' are those that were part of the mask at higher resolution," + 
              "but were filtered out using the lower resolution mask. If there are still unwanted 'floating clusters'" +
              "in the final mask, edit the 'scale' parameter to higher integer number. Eg. 'scale=2'-> 'scale=3'.")
        print()

    
    # elif solver == 'expansion':
        # ....

    else:
        print('ERROR! Invalid input for "solver" argument. Options are "infill" or "expansion".')

    #Finally, we remove stray points from both objects if the user requests it.
    if smooth ==True:
        print("Applying iterative smoothing:")
        print()

        #Print both the pre- and post-smoothing image.
        fig, axes = plt.subplots(1, 2, figsize=(12, 6))
        
        #sns.scatterplot(data=exp_bin_df, x='X_quant', y='Y_quant', hue='Mask', ax=axes[0], s=(d_scale(exp_bin_df)))
        #axes[0].set_title("Scatterplot of Pre-Smoothing Mask")

        pivot_table = mk_pivot(exp_bin_df, q_factor=quant_factor, z='Mask', fill=2)
        sns.heatmap(pivot_table, cmap='viridis', cbar=False, linewidths=lines, linecolor='white', alpha=0.8, ax=axes[0])
        axes[0].set_title("Scatterplot of Pre-Smoothing Mask")
        axes[0].set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
        axes[0].set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
        # axes[0,1].collections[0].cmap.set_bad('w') #Setting a white background here.


        #Apply smoothing:
        exp_bin_df, white_matter_df = iter_smooth(exp_bin_df, white_matter_df, q_factor=quant_factor)
        print()

        #Post smoothing:
        
        #sns.scatterplot(data=exp_bin_df, x='X_quant', y='Y_quant', hue='Mask', ax=axes[1], s=(d_scale(exp_bin_df)))
        #axes[1].set_title("Scatterplot of Post-Smoothing Mask")

        pivot_table = mk_pivot(exp_bin_df, q_factor=quant_factor, z='Mask', fill=2)
        sns.heatmap(pivot_table, cmap='viridis', cbar=False, linewidths=lines, linecolor='white', alpha=0.8, ax=axes[1])
        axes[1].set_title("Scatterplot of Post-Smoothing Mask")
        axes[1].set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
        axes[1].set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
        # axes[0,1].collections[0].cmap.set_bad('w') #Setting a white background here.
        
        
    else:
        #Print the mask as-is.
        
        #fig, axes = plt.subplots(1, 1, figsize=(6, 6))
        #sns.scatterplot(data=exp_bin_df, x='X_quant', y='Y_quant', hue='Mask', s=(d_scale(exp_bin_df)))
        #axes.set_title("Scatterplot of Mask")

        fig, axes = plt.subplots(1, 1, figsize=(6, 6))
        
        pivot_table = mk_pivot(exp_bin_df, q_factor=quant_factor, z='Mask', fill=2)
        sns.heatmap(pivot_table, cmap='viridis', cbar=False, linewidths=lines, linecolor='white', alpha=0.8, ax=axes)
        # --Bug Fix! 11.11.25
        axes.set_title("Scatterplot of Final Mask")
        axes.set_xlim(0, (max(exp_bin_df['X_quant'])/q_factor)+1)
        axes.set_ylim(0, (max(exp_bin_df['Y_quant'])/q_factor)+1)
        # axes[0,1].collections[0].cmap.set_bad('w') #Setting a white background here.
    

    # Adjust layout for better spacing
    plt.tight_layout()

    if fig_path != None:
        fig.savefig(fig_path+'Final.png', dpi=300)

    # Show the plots
    plt.show()

    #We can also export our tables to the same folder for very little extra work:
    if fig_path != None:
        white_matter_df.to_csv(fig_path+'annotated_raw_positions.csv')
        exp_bin_df.to_csv(fig_path+'quantized_positions.csv')
    
    print("Annotated raw positions are now stored in the first output object. For quantized positions, see the second (smaller) object.")
    if fig_path != None:
        print("All outputs successfuly saved to folder:", fig_path)
    
    return white_matter_df, exp_bin_df

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #2bebdada-121d-44e5-9011-f17dbdf160f9
def mk_pivot_table(df,q_factor):
    #To impute the background, make a blank matrix of all possible positions, given
    # 1. Start by filling in the background.
    area = max(max(df['X_quant']), max(df['Y_quant'])) + q_factor/2
            
    matr = []
    r = int(area/q_factor)

    #We later trim this mask to the right size, so let's focus on making sure we have enough space.
    #Notice that we've applied 'iter_smooth', wo we can't quite trust the current size of our dataframe.
    for i in range (0, r+20):
      for j in range (0, r+20):
          matr.append([float((i+0.5)*q_factor), float((j+0.5)*q_factor)])
    
    matr = pd.DataFrame(matr, columns = ['X_quant', 'Y_quant'])
    
    #Add an empty "mask" to mark all the background points.
    # matr['Mask'] = 2
    
    #matr
    
    matr = pd.merge(matr, df, on=['X_quant', 'Y_quant'], how='left')
    #And let's fill in blank positions in the mask.
    matr['Mask'] = matr['Mask'].fillna(2)

    #2. Convert to pivot table.
    pivot_table = matr.pivot(index='Y_quant', columns='X_quant', values='Mask')
    #Note that the columns seem backwards here, but that's necessary for it to render the way we want it to.

    #And convert to Numpy array:
    pivot_table = np.array(pivot_table)

    #plt.imshow(matr_2d, interpolation="nearest", origin="lower")
    plt.imshow(pivot_table, origin="lower")
    plt.colorbar()
    plt.show()

    return(pivot_table)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #e38b509b-a6f5-45b2-9153-f54f2e1f00ba
def matr_expand(pivot_table, q_factor, factor):
    print('factor: ', factor)
    print('final resolution: ', q_factor/factor)
    
    expanded_matrix = np.kron(pivot_table, np.ones((factor, factor)))
    
    print('shape of matrix',expanded_matrix.shape)
    
    return(expanded_matrix)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #6155dfd4-8cd4-4241-8123-4a11a1adea9e
import cv2
import tifffile as tf

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #69941136-7c85-4efc-afa4-68d743a38a63
def image_trim(expanded_matrix, path):
    try:
        image = cv2.imread(path)
    except cv2.error:
        image = tf.imread(path)
        
    print('Shape of reference image: ', image.shape)
    expanded_matrix__ = expanded_matrix[0:image.shape[0], 0:image.shape[1]]

    #Explicitly tell Python to delete the massive image file as soon as we're done with it:
    del image
    
    return(expanded_matrix__)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #ab0fc1ee-faa5-4b8c-a59b-58d60737333d
def tiff_write(x, output_path):
    
    #x = np.load(path)
    #output_path =  (path[:-4]+'.tiff')
    
    with tf.TiffWriter(output_path, bigtiff = True) as tif:
        options = dict(photometric = 'minisblack',
                       compression = "zlib")
        tif.write(x, **options)
    
        print('Written to:' + output_path)

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #b17f8d7c-6ff8-430b-9b6b-bf28d8894733
from skimage import exposure
#import tiffile as tf

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #2f194108-dbb2-4969-90a8-fd3d0106e583
def img_disp (img_path, annot, l=7, fig_path=None):
    #Level 2 contains a much smaller version of the file than the full-sized ome.tif
    downsampled_img = tf.imread(img_path, level=2)

    #Used to enhance contrast. --We also generally select layer 7 because it generally contains the full image of cells in the tissue sample.
    enhanced_img = exposure.equalize_adapthist(downsampled_img, #[l], 
        clip_limit=0.05 # Adjust this value (e.g., 0.005 to 0.03) for desired effect
    )

    # 1. Plot the original image.
    fig, ax = plt.subplots(figsize=(16, 12)) 
    ax.imshow(enhanced_img, origin="lower")
    # 2. Plot the mask.
    ax.imshow(annot[::4, ::4], origin="lower", alpha=0.3)
    #ax.imshow(annot[::4, ::4], origin="lower", alpha=0.3)

    #Display the figure:
    ax.set_title("Overlay of Mask With Down-Sampled ome.tif File")
    plt.show()

    #Output the  figure if user has provided a path to do so:
    if fig_path != None:
        fig.savefig(fig_path+'Mask_Over_Tissue_Outline.png', dpi=300)
        print('Written to:'+fig_path+'Mask_Over_Tissue_Outline.png')
        

# %% ../white_matter_module_2_DEVELOPMENT_contdx5_3_12_12_25_backup-Mult_Complex_Infill.ipynb #ecf07206-4420-4091-a3f9-ee21bd6c2262
def mk_tiff(exp_bin_df, ref, outf, q_factor=85, factor=400):
    #Make the initial pivot table.
    pivot_table = mk_pivot_table(exp_bin_df, q_factor)
    #Expand the matrix according to the factor provided.
    expanded_matrix = matr_expand(pivot_table, q_factor, factor)
    #And trim to the right size based on the .tiff file provided.
    expanded_matrix__ = image_trim(expanded_matrix, ref)

    plt.imshow(expanded_matrix__[::factor, ::factor], origin="lower")
    plt.colorbar()
    plt.show()
    
    #Write as .tiff file
    tiff_write(expanded_matrix__, (outf+'array_file.tiff'))

    print('[Now generating the image of the final mask overlaid onto morphology...]')

    #And finally call in 'img_disp' to display the mask overlaid onto the morphology:
    img_disp(img_path=ref, annot=expanded_matrix__,
        fig_path=outf)
    

    return()
